// Generated by @clerk/mobile-runtime pack. Do not edit.
package com.clerk.api
public object BundledCore {
  public const val sha256: String = "11c3182aa2585c3212037e6182bf9e35dfed51f75d7cfda1f65535c07efe2e15"
  public const val coreRevision: String = "29de5049111f3ebcb5bea299ec3f7e4d29844cf3"
}
