// Generated by @clerk/mobile-runtime pack. Do not edit.
package com.clerk.api
public object BundledCore {
  public const val sha256: String = "b2fd61d11f6755a8962f2e64456e18478d3efb6cfc8d391acf44e018507929f0"
  public const val coreRevision: String = "808d40357bef5e725efed829b9ff3a4088af584b"
}
