// Generated by @clerk/mobile-runtime pack. Do not edit.
package com.clerk.api
public object BundledCore {
  public const val sha256: String = "7092632548bac2524f1b74a798e6c0725bc48e05316cefa1da5315cd08dc151e"
  public const val coreRevision: String = "208cfe269a63c339da5623bb8428dbe15dbc58f8"
}
