name: reviewdog
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  detekt:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    name: Check Code Quality
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Clone repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: alaegin/Detekt-Action@v1.23.8
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
          detekt_baseline: config/detekt/detekt-baseline.xml
